//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cproj.rc
//
#define IDS_INFOTEXT                    101
#define IDD_CONTROLS                    131
#define IDD_INFO                        132
#define IDC_EDIT_01                     1012
#define IDC_EDIT_02                     1015
#define IDC_EDIT_03                     1016
#define IDC_EDIT_04                     1018
#define IDC_EDIT_05                     1013
#define IDC_EDIT_06                     1021
#define IDC_EDIT_07                     1019
#define IDC_EDIT_08                     1020
#define IDC_EDIT_09                     1014
#define IDC_EDIT_10                     1024
#define IDC_EDIT_11                     1022
#define IDC_EDIT_12                     1023
#define IDC_EDIT_13                     1017
#define IDC_EDIT_14                     1027
#define IDC_EDIT_15                     1025
#define IDC_EDIT_16                     1026
#define IDC_EDIT                        1030

#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
